plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  SuggestExtensions: false

Metrics/BlockLength:
  Exclude:
    - "*.gemspec"
    - spec/**/*
Metrics/ClassLength:
  Exclude:
    - lib/legion/extensions/llm/vllm/provider.rb
Metrics/MethodLength:
  Enabled: false
RSpec/ExampleLength:
  Max: 8
RSpec/MultipleExpectations:
  Enabled: false
